package CalculadoraApp;


/**
* CalculadoraApp/_CalculadoraImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Friday, September 18, 2026 9:42:44 PM UTC
*/

public abstract class _CalculadoraImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements CalculadoraApp.Calculadora, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CalculadoraImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("somar", new java.lang.Integer (0));
    _methods.put ("subtrair", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CalculadoraApp/Calculadora/somar
       {
         double numero1 = in.read_double ();
         double numero2 = in.read_double ();
         double $result = (double)0;
         $result = this.somar (numero1, numero2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // CalculadoraApp/Calculadora/subtrair
       {
         double numero1 = in.read_double ();
         double numero2 = in.read_double ();
         double $result = (double)0;
         $result = this.subtrair (numero1, numero2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/Calculadora:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CalculadoraImplBase
