package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Friday, September 18, 2026 11:02:10 PM UTC
*/

public interface CalculadoraOperations 
{
  double somar (double numero1, double numero2);
  double subtrair (double numero1, double numero2);
} // interface CalculadoraOperations
