package CalculadoraApp;


/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Friday, September 18, 2026 11:02:10 PM UTC
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
