// Arquivo Calculadora.idl:

module CalculadoraApp {
  interface Calculadora {
    double somar(in double numero1, in double numero2);
    double subtrair(in double numero1, in double numero2);
  };
};